### ISSUE TITLE
Use general name as a session key

### ISSUE THREAD

**Issue by mkorkmaz** [hkulekci/zend-expressive-skeleton#1]
https://github.com/hkulekci/zend-expressive-skeleton/blob/5c7cbfe75c53ce6dd17f662b98d44dba31e0b4df/src/App/src/Authentication/AuthenticationMiddleware.php#L18

**Comment by hkulekci** [comment]
Thank you. You know, a copy-paste issue. I will move this logic to the configuration.

**Comment by hkulekci** [comment]
fixed.
